// Code generated by MockGen. DO NOT EDIT.
// Source: post.go

// Package mock_post is a generated GoMock package.
package mock_post

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	post "github.com/islombay/blogPost/internal/service/post"
)

// MockPostServiceInterface is a mock of PostServiceInterface interface.
type MockPostServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceInterfaceMockRecorder
}

// MockPostServiceInterfaceMockRecorder is the mock recorder for MockPostServiceInterface.
type MockPostServiceInterfaceMockRecorder struct {
	mock *MockPostServiceInterface
}

// NewMockPostServiceInterface creates a new mock instance.
func NewMockPostServiceInterface(ctrl *gomock.Controller) *MockPostServiceInterface {
	mock := &MockPostServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPostServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostServiceInterface) EXPECT() *MockPostServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockPostServiceInterface) Create(m post.CreateModel) (post.PostModel, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", m)
	ret0, _ := ret[0].(post.PostModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostServiceInterfaceMockRecorder) Create(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostServiceInterface)(nil).Create), m)
}

// Delete mocks base method.
func (m *MockPostServiceInterface) Delete(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostServiceInterfaceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostServiceInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockPostServiceInterface) GetAll() ([]post.PostModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]post.PostModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPostServiceInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPostServiceInterface)(nil).GetAll))
}
